EXCHANGE_RATES_LINK = "//a[@data-cga_click_extra_link =\"Курсы валют\"]"
GEOPOSITION_LINK = "//a[@title=\"Изменить регион\"]"
FIRST_TITLE_ON_PAGE = "//h1"
REGION_NAME_FIELD = "//input[@aria-label=\"Введите имя региона\"]"
ROSTOV_REGION_FIELD = "//button [text()=\"Ростовская область\"]"
SBERONLINE_LINK = "//a[text()=\"СберБанк Онлайн\"]"
OFFICES_LINK = "//a[@data-cga_click_extra_link =\"Курсы валют\"]/following::a[1]"
ATM_LINK = "//a[@data-cga_click_extra_link =\"Курсы валют\"]/following::a[2]"
OPEN_SEARCH_LINK = "//a[@aria-label=\"Открыть поиск по сайту\"]"
SEARCH_FIELD_LINK = "//input[@aria-label=\"Поиск по сайту\"]"